packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - '@clerk/shared'
  - '@vercel/speed-insights'
  - core-js
  - esbuild
  - sharp
  - unrs-resolver

catalog:
  react: 19.2.1
  react-dom: 19.2.1
  "@types/react": 19.2.1
  "@types/react-dom": 19.2.1
